name: Build Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Android Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk

      - name: Install node_modules at Root
        uses: ./.github/actions/setup-node
        with:
          working-directory: ./

      - name: Build Library
        run: yarn build

      - name: Install node_modules at Example
        uses: ./.github/actions/setup-node
        with:
          working-directory: example

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Build for example
        run: cd example/android && ./gradlew assembleDebug --build-cache && cd ../../..

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Build Android
          path: example/android/app/build/outputs/apk/debug/app-debug.apk